# CSC 4792 DATA MINING AND WAREHOUSING MINI PROJECT

## Team 7 — Chingola Municipal Council

### Project Title
**Data Mining and Warehousing of Chingola Municipal Council Digital Footprints**

### Dataset
Chingola Municipal Council Dataset

### Data Source
Kaggle: Chingola Municipal Council Dataset

### Objective

The objective of this project is to collect, curate, clean, preprocess,
analyse and mine publicly available digital data relating to Chingola
Municipal Council.

The project integrates information relating to:

- Council budgets
- Revenue
- Expenditure
- CDF applications and projects
- Capital projects
- IDP strategic outputs
- Citizen engagement
- Debt and arrears
- Internal audit
- Budget and project performance

The analysis aims to identify useful patterns, trends, relationships and
performance indicators within the Chingola Municipal Council data.

In [ ]:
##upload zip file



```
# This is formatted as code
```# Find uploaded ZIP file
zip_files = [f for f in uploaded.keys() if f.lower().endswith(".zip")]

if len(zip_files) == 0:
    raise FileNotFoundError("No ZIP file was uploaded.")

zip_path = zip_files[0]

# Create extraction directory
extract_dir = "chingola_dataset"

os.makedirs(extract_dir, exist_ok=True)

# Extract
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_dir)

print("Dataset extracted successfully.")
print("Location:", extract_dir)

In [ ]:
# ============================================================
# CSC 4792 - DATA MINING AND WAREHOUSING
# TEAM 7 - CHINGOLA MUNICIPAL COUNCIL
# ============================================================

import os
import glob
import zipfile
import warnings
import re

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

print("All libraries imported successfully.")

All libraries imported successfully.

In [ ]:
from google.colab import files
import os
import zipfile

uploaded = files.upload()

Saving archive (1).zip to archive (1) (2).zip

In [ ]:
all_files = []

for root, directories, files_in_folder in os.walk(extract_dir):
    for file in files_in_folder:
        all_files.append(os.path.join(root, file))

print(f"Total files found: {len(all_files)}\n")

for file in all_files:
    print("-", file)

Total files found: 23

- chingola_dataset/db-unza26-csc4792-chingola_semiannual_revenue_2025.csv
- chingola_dataset/db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv
- chingola_dataset/db-unza26-csc4792-chingola_semiannual_payments_2025.csv
- chingola_dataset/db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv
- chingola_dataset/db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv
- chingola_dataset/db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv
- chingola_dataset/db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv
- chingola_dataset/db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv
- chingola_dataset/db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv
- chingola_dataset/db-unza26-csc4792-chingola_cdf_2025_applications.csv
- chingola_dataset/db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv
- chingola_dataset/db-unza26-csc4792-chingola_capital_output_2024.csv
- chingola_dataset/db-unza26-csc4792-chingola_cdf_2024_applications.csv
- chingola_dataset/db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv
- chingola_dataset/db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv
- chingola_dataset/db-unza26-csc4792-nchanga_cdf_2025_applications.csv
- chingola_dataset/db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv
- chingola_dataset/db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv
- chingola_dataset/db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv
- chingola_dataset/db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv
- chingola_dataset/db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv
- chingola_dataset/db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv
- chingola_dataset/db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv

In [ ]:
csv_files = [
    file for file in all_files
    if file.lower().endswith(".csv")
]

print(f"Total CSV files: {len(csv_files)}")

for file in csv_files:
    print("-", os.path.basename(file))

Total CSV files: 23
- db-unza26-csc4792-chingola_semiannual_revenue_2025.csv
- db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv
- db-unza26-csc4792-chingola_semiannual_payments_2025.csv
- db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv
- db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv
- db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv
- db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv
- db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv
- db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv
- db-unza26-csc4792-chingola_cdf_2025_applications.csv
- db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv
- db-unza26-csc4792-chingola_capital_output_2024.csv
- db-unza26-csc4792-chingola_cdf_2024_applications.csv
- db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv
- db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv
- db-unza26-csc4792-nchanga_cdf_2025_applications.csv
- db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv
- db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv
- db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv
- db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv
- db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv
- db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv
- db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv

In [ ]:
raw_data = {}

for file in csv_files:

    filename = os.path.basename(file)

    try:
        df = pd.read_csv(
            file,
            sep="|",
            encoding="utf-8"
        )

        raw_data[filename] = df

        print(
            f"{filename}: "
            f"{df.shape[0]} rows × {df.shape[1]} columns"
        )

    except Exception as e:
        print(f"ERROR reading {filename}: {e}")

db-unza26-csc4792-chingola_semiannual_revenue_2025.csv: 17 rows × 9 columns
db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv: 5 rows × 10 columns
db-unza26-csc4792-chingola_semiannual_payments_2025.csv: 8 rows × 8 columns
db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv: 13 rows × 11 columns
db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv: 5 rows × 4 columns
db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv: 10 rows × 4 columns
db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv: 15 rows × 5 columns
db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv: 5 rows × 7 columns
db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv: 139 rows × 16 columns
db-unza26-csc4792-chingola_cdf_2025_applications.csv: 86 rows × 16 columns
db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv: 5 rows × 5 columns
db-unza26-csc4792-chingola_capital_output_2024.csv: 10 rows × 9 columns
db-unza26-csc4792-chingola_cdf_2024_applications.csv: 58 rows × 12 columns
db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv: 16 rows × 6 columns
db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv: 7 rows × 4 columns
db-unza26-csc4792-nchanga_cdf_2025_applications.csv: 48 rows × 16 columns
db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv: 7 rows × 5 columns
db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv: 6 rows × 8 columns
db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv: 55 rows × 8 columns
db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv: 100 rows × 4 columns
db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv: 177 rows × 6 columns
db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv: 14 rows × 5 columns
db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv: 8 rows × 7 columns

In [ ]:
dataset_inventory = []

for filename, df in raw_data.items():

    dataset_inventory.append({
        "Dataset": filename,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "MissingValues": int(df.isna().sum().sum()),
        "DuplicateRows": int(df.duplicated().sum())
    })

inventory_df = pd.DataFrame(dataset_inventory)

inventory_df = inventory_df.sort_values(
    by="Rows",
    ascending=False
)

display(inventory_df)

,Dataset,Rows,Columns,MissingValues,DuplicateRows
20,db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv,177,6,0,0
8,db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv,139,16,537,0
19,db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv,100,4,6,0
9,db-unza26-csc4792-chingola_cdf_2025_applications.csv,86,16,319,0
12,db-unza26-csc4792-chingola_cdf_2024_applications.csv,58,12,81,0
18,db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv,55,8,0,0
15,db-unza26-csc4792-nchanga_cdf_2025_applications.csv,48,16,123,0
0,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,17,9,0,0
13,db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv,16,6,0,0
6,db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv,15,5,0,0
21,db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv,14,5,0,0
3,db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv,13,11,21,0
11,db-unza26-csc4792-chingola_capital_output_2024.csv,10,9,0,0
5,db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv,10,4,0,0
2,db-unza26-csc4792-chingola_semiannual_payments_2025.csv,8,8,0,0
22,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,8,7,0,0
14,db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv,7,4,0,0
16,db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv,7,5,0,0
17,db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv,6,8,1,0
4,db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv,5,4,0,0
1,db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv,5,10,0,0
7,db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv,5,7,0,0
10,db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv,5,5,0,0

In [ ]:
for filename, df in raw_data.items():

    print("\n" + "=" * 100)
    print(filename)
    print("=" * 100)

    print("Shape:", df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 3 records:")
    display(df.head(3))

====================================================================================================
db-unza26-csc4792-chingola_semiannual_revenue_2025.csv
====================================================================================================
Shape: (17, 9)

Columns:
['Section', 'Code', 'Receipt', 'BudgetZMW', 'ActualTo30Jun2025ZMW', 'VarianceZMW', 'PerformancePercent', 'ReportPeriod', 'SourceDocument']

First 3 records:

,Section,Code,Receipt,BudgetZMW,ActualTo30Jun2025ZMW,VarianceZMW,PerformancePercent,ReportPeriod,SourceDocument
0,National Support,1.1,Local Government Equalisation Fund,12000000,4121737,7878263,34,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
1,National Support,1.2,Grants In Lieu of Rates,0,0,0,0,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
2,National Support,1.3,Sector Grants,17982476,2248542,15733934,13,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf

====================================================================================================
db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv
====================================================================================================
Shape: (5, 10)

Columns:
['ProjectNo', 'ProgrammeProject', 'OutputIndicator', 'Target', 'ZMTotalCost', 'Location', 'SourceOfFunding', 'TimeframeStatus', 'PlanPeriod', 'SourceDocument']

First 3 records:

,ProjectNo,ProgrammeProject,OutputIndicator,Target,ZMTotalCost,Location,SourceOfFunding,TimeframeStatus,PlanPeriod,SourceDocument
0,1,Construction of Fire station,Fire station constructed (Phase 1),1,"K1,600,000.00",Council Parks and Gardens in Chingola Central Ward,CMC,Ongoing,2024-2033,"CHINGOLA-IDP.pdf (Table 48, page 225)"
1,2,Construction / Expansion Health Centres,No. of Health Posts/Centres constructed/expanded,1,"K7,000,000.00",Selected ward,CDF,Not yet,2024-2033,"CHINGOLA-IDP.pdf (Table 48, page 225)"
2,3,Construction of Classroom Blocks,No. of Classroom blocks constructed,14,"K12,600,000.00",Selected wards,CDF,Ongoing,2024-2033,"CHINGOLA-IDP.pdf (Table 48, page 225)"

====================================================================================================
db-unza26-csc4792-chingola_semiannual_payments_2025.csv
====================================================================================================
Shape: (8, 8)

Columns:
['Code', 'PaymentCategory', 'BudgetZMW', 'ActualTo30Jun2025ZMW', 'VarianceZMW', 'PerformancePercent', 'ReportPeriod', 'SourceDocument']

First 3 records:

,Code,PaymentCategory,BudgetZMW,ActualTo30Jun2025ZMW,VarianceZMW,PerformancePercent,ReportPeriod,SourceDocument
0,1,Personal emoluments,67183236,32820761,34362475,49,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
1,2,Use of goods and services,55005085,24943955,30061130,45,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
2,3,Financial charges,0,0,0,0,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf

====================================================================================================
db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv
====================================================================================================
Shape: (13, 11)

Columns:
['S/N', 'ProjectName', 'StartDate', 'EndDate', 'ContractAmountZMW', 'CumulativePaymentsTo30Jun2025ZMW', 'BalanceZMW', 'SourceOfFunds', 'ProjectStatus', 'ReportPeriod', 'SourceDocument']

First 3 records:

,S/N,ProjectName,StartDate,EndDate,ContractAmountZMW,CumulativePaymentsTo30Jun2025ZMW,BalanceZMW,SourceOfFunds,ProjectStatus,ReportPeriod,SourceDocument
0,1,Procurement of a Computer Server,NaN,NaN,350000,0.0,350000.0,LOCAL RESOURCES,WIP,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
1,2,Construction of Two Guard Houses at Civic Centre,3-Mar-2025,30/05/2025,300000,300000.0,0.0,LOCAL RESOURCES,Completed,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
2,3,Construction of Ablution Block at Kapisha Cemetery,NaN,NaN,250000,0.0,250000.0,LOCAL RESOURCES,WIP,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf

====================================================================================================
db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv
====================================================================================================
Shape: (5, 4)

Columns:
['Type', 'Statement', 'StrategyPeriod', 'SourceDocument']

First 3 records:

,Type,Statement,StrategyPeriod,SourceDocument
0,Vision,"Creating an inclusive, transparent and participatory context that empowers citizens to contribut...",Five years,citizen-engagement-strategy-.pdf
1,Aim,The main aim of this Strategy is to provide a structured approach for engaging citizens in the b...,Five years,citizen-engagement-strategy-.pdf
2,Objective 1,Increase current levels of citizen awareness and understanding of the budget and project cycle p...,Five years,citizen-engagement-strategy-.pdf

====================================================================================================
db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv
====================================================================================================
Shape: (10, 4)

Columns:
['FundingSource', 'Year', 'AmountZMW', 'SourceDocument']

First 3 records:

,FundingSource,Year,AmountZMW,SourceDocument
0,Constituency Development Fund for 2 constituencies,2019,1000000.0,CHINGOLA-IDP.pdf
1,Constituency Development Fund for 2 constituencies,2020,3200000.0,CHINGOLA-IDP.pdf
2,Constituency Development Fund for 2 constituencies,2021,3200000.0,CHINGOLA-IDP.pdf

====================================================================================================
db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv
====================================================================================================
Shape: (15, 5)

Columns:
['Narration', 'OutstandingAmount1Jan2025ZMW', 'OutstandingAmount30Jun2025ZMW', 'ReportPeriod', 'SourceDocument']

First 3 records:

,Narration,OutstandingAmount1Jan2025ZMW,OutstandingAmount30Jun2025ZMW,ReportPeriod,SourceDocument
0,PES,0.0,0.0,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
1,ZAMTEL,0.0,0.0,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
2,ZESCO,0.0,0.0,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf

====================================================================================================
db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv
====================================================================================================
Shape: (5, 7)

Columns:
['DeliverableActivity', 'TargetStakeholders', 'Frequency', 'ProposedTimeline', 'Responsibility', 'CommunicationMethod', 'SourceDocument']

First 3 records:

,DeliverableActivity,TargetStakeholders,Frequency,ProposedTimeline,Responsibility,CommunicationMethod,SourceDocument
0,Budget formulated,"WDCs, and community and all stakeholders involved",Annually,August to November,Council and all stakeholders,Community meetings with all stakeholders,citizen-engagement-strategy-.pdf
1,Budget approved,All stakeholders,Annually,November/December,Council and all stakeholders,Full Council meeting,citizen-engagement-strategy-.pdf
2,Budget executed and monitored,All stakeholders,Throughout the year,Throughout the year,Council and stakeholders,Community meeting,citizen-engagement-strategy-.pdf

====================================================================================================
db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv
====================================================================================================
Shape: (139, 16)

Columns:
['ProjectID', 'Year', 'Constituency', 'ProjectName', 'ProjectDescription', 'Sector', 'ProjectType', 'Ward', 'Zone', 'DistanceFromCBD', 'EstimatedCost', 'RecommendedAmount', 'ApprovalStatus', 'Comments', 'TechnicalAppraisalRecommendations', 'SourceDocument']

First 3 records:

,ProjectID,Year,Constituency,ProjectName,ProjectDescription,Sector,ProjectType,Ward,Zone,DistanceFromCBD,EstimatedCost,RecommendedAmount,ApprovalStatus,Comments,TechnicalAppraisalRecommendations,SourceDocument
0,CHG-CDF-2024-001,2024,Chingola,Procurement of Ambulance,Procurement of an ambulance,NaN,Procurement,All wards,NaN,NaN,2700000.0,2700000.0,Approved,NaN,NaN,Chingola Constituency 2024 Approved CDF Community Projects
1,CHG-CDF-2024-002,2024,Chingola,Paving of Chikola Shopping Complex,Paving of the shopping complex,NaN,Construction,Chikola,NaN,NaN,1600000.0,1600000.0,Approved,NaN,NaN,Chingola Constituency 2024 Approved CDF Community Projects
2,CHG-CDF-2024-003,2024,Chingola,Refurbishment of Kalilo Clinic,Refurbishment of Kalilo Clinic,NaN,Rehabilitation,Kalilo,NaN,NaN,800000.0,800000.0,Approved,NaN,NaN,Chingola Constituency 2024 Approved CDF Community Projects

====================================================================================================
db-unza26-csc4792-chingola_cdf_2025_applications.csv
====================================================================================================
Shape: (86, 16)

Columns:
['ProjectID', 'Year', 'Constituency', 'ProjectName', 'ProjectDescription', 'Sector', 'ProjectType', 'Ward', 'ApprovedApplication', 'EngineersEstimate', 'FurnitureCost', 'RecommendedAmount', 'YearFunded', 'ApprovalStatus', 'Comments', 'SourceDocument']

First 3 records:

,ProjectID,Year,Constituency,ProjectName,ProjectDescription,Sector,ProjectType,Ward,ApprovedApplication,EngineersEstimate,FurnitureCost,RecommendedAmount,YearFunded,ApprovalStatus,Comments,SourceDocument
0,CHG-2025-APP-001,2025,Chingola,Construction of ablution block at Musenga Primary School,construction of ablution block at Musenga Primary School,Water and sanitation,Construction,Musenga,Yes,800000.0,NaN,800000.0,2025.0,Approved,NaN,Chingola Constituency 2025 CDF Community Projects Applications
1,CHG-2025-APP-002,2025,Chingola,Construction of 1X3 classroom block at Musenga Primary School,construction of a 1X3 classroom block,Education,Construction,Musenga,No,NaN,NaN,NaN,NaN,Not approved,Not approved due to limited funds,Chingola Constituency 2025 CDF Community Projects Applications
2,CHG-2025-APP-003,2025,Chingola,Sinking and equipping boreholes,sinking and equipping four (4) boreholes,Water and sanitation,Drilling and equipping,Musenga,Yes,295000.0,NaN,295000.0,2025.0,Approved,NaN,Chingola Constituency 2025 CDF Community Projects Applications

====================================================================================================
db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv
====================================================================================================
Shape: (5, 5)

Columns:
['Year', 'BudgetZMW', 'ActualRevenueZMW', 'EfficiencyPercent', 'SourceDocument']

First 3 records:

   Year  BudgetZMW  ActualRevenueZMW  EfficiencyPercent    SourceDocument
0  2018   64976297          41360216                 64  CHINGOLA-IDP.pdf
1  2019   62962330          41944095                 67  CHINGOLA-IDP.pdf
2  2020   65641096          56048686                 85  CHINGOLA-IDP.pdf

====================================================================================================
db-unza26-csc4792-chingola_capital_output_2024.csv
====================================================================================================
Shape: (10, 9)

Columns:
['Year', 'ProgrammeProject', 'Description', 'Status', 'PercentageComplete', 'Constituency', 'Ward', 'Budget2024', 'SourceDocument']

First 3 records:

,Year,ProgrammeProject,Description,Status,PercentageComplete,Constituency,Ward,Budget2024,SourceDocument
0,2024,Housing and Community Amenities,Paving of ZISC Parking Area,Not Yet Mobilised,0%,Nchanga,Nchanga,1100000,Capital Output Location Annex
1,2024,Housing and Community Amenities,Drainage Clearing in Wards before and after the rains,Not Yet Mobilised,0%,All Constituencies,All Wards,600000,Capital Output Location Annex
2,2024,Housing and Community Amenities,WDF Projects (K268K*29),Not Yet Mobilised,0%,All Constituencies,All Wards,7772000,Capital Output Location Annex

====================================================================================================
db-unza26-csc4792-chingola_cdf_2024_applications.csv
====================================================================================================
Shape: (58, 12)

Columns:
['ProjectID', 'Year', 'Constituency', 'ProjectName', 'ProjectDescription', 'ProjectType', 'Ward', 'EstimatedCost', 'RecommendedAmount', 'ApprovalStatus', 'Comments', 'SourceDocument']

First 3 records:

,ProjectID,Year,Constituency,ProjectName,ProjectDescription,ProjectType,Ward,EstimatedCost,RecommendedAmount,ApprovalStatus,Comments,SourceDocument
0,CHG-APP-2024-001,2024,Chingola,Procurement of Ambulance,Procurement of Ambulance,Health,All wards,2700000.0,2700000.0,Approved,NaN,Chingola Constituency 2024 CDF Community Projects Applications
1,CHG-APP-2024-002,2024,Chingola,Paving of Chikola Shopping Complex,Paving of Chikola Shopping Complex,Roads,Chikola,1600000.0,1600000.0,Approved,NaN,Chingola Constituency 2024 CDF Community Projects Applications
2,CHG-APP-2024-003,2024,Chingola,Refurbishment of Kalilo Clinic,Refurbishment of Kalilo Clinic,Health,Kalilo,800000.0,800000.0,Approved,NaN,Chingola Constituency 2024 CDF Community Projects Applications

====================================================================================================
db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv
====================================================================================================
Shape: (16, 6)

Columns:
['ProgrammeCode', 'Programme', 'Budget2024ZMW', 'Budget2025ZMW', 'Budget2026ZMW', 'SourceDocument']

First 3 records:

,ProgrammeCode,Programme,Budget2024ZMW,Budget2025ZMW,Budget2026ZMW,SourceDocument
0,1,Constituency Development,61271284,72116301,80065100,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf
1,2,Local Governance,4266553,4021122,4669539,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf
2,3,Integrated Development Planning,3752039,6653932,6313730,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf

====================================================================================================
db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv
====================================================================================================
Shape: (7, 4)

Columns:
['OutputID', 'StrategicOutput', 'PlanPeriod', 'SourceDocument']

First 3 records:

,OutputID,StrategicOutput,PlanPeriod,SourceDocument
0,1,A diversified economic development through enhanced investment in all sectors to create wealth a...,2024-2033,CHINGOLA-IDP.pdf
1,2,"Availability and sustainable management of clean, safe water and sanitation for all",2024-2033,CHINGOLA-IDP.pdf
2,3,"Improved literacy levels through quality, equitable and inclusive education",2024-2033,CHINGOLA-IDP.pdf

====================================================================================================
db-unza26-csc4792-nchanga_cdf_2025_applications.csv
====================================================================================================
Shape: (48, 16)

Columns:
['ProjectID', 'Year', 'Constituency', 'ProjectName', 'ProjectDescription', 'Sector', 'ProjectType', 'Ward', 'ApprovedApplication', 'EngineersEstimate', 'FurnitureCost', 'RecommendedAmount', 'YearFunded', 'ApprovalStatus', 'Comments', 'SourceDocument']

First 3 records:

,ProjectID,Year,Constituency,ProjectName,ProjectDescription,Sector,ProjectType,Ward,ApprovedApplication,EngineersEstimate,FurnitureCost,RecommendedAmount,YearFunded,ApprovalStatus,Comments,SourceDocument
0,NCH-2025-APP-001,2025,Nchanga,Completion of a 1x4 Classroom Block at Luano Combined School,Completion of a 1x4 Classroom Block,Education,Construction,Kapisha,Yes,1300000.0,NaN,1300000.0,2025,Approved,NaN,Nchanga Constituency 2025 CDF Community Projects Applications
1,NCH-2025-APP-002,2025,Nchanga,Completion of a Charcoal Shelter at Chilemba Market,Completion of a Charcoal Shelter,Markets and Bus station,Construction,Kapisha,Yes,920000.0,NaN,920000.0,2025,Approved,NaN,Nchanga Constituency 2025 CDF Community Projects Applications
2,NCH-2025-APP-003,2025,Nchanga,Construction of a Chicken Shelter at Chilemba Market,Construction of a Chicken Shelter,Markets and Bus station,Construction,Kapisha,Yes,102000.0,NaN,102000.0,2025,Approved,NaN,Nchanga Constituency 2025 CDF Community Projects Applications

====================================================================================================
db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv
====================================================================================================
Shape: (7, 5)

Columns:
['EconomicClassification', 'Budget2024ZMW', 'Budget2025ZMW', 'Budget2026ZMW', 'SourceDocument']

First 3 records:

,EconomicClassification,Budget2024ZMW,Budget2025ZMW,Budget2026ZMW,SourceDocument
0,Personal Emoluments,66949066,67183236,71783764,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf
1,Goods and Services,49411622,56141725,78784748,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf
2,Social Assistance Benefits,0,21789540,8745211,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf

====================================================================================================
db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv
====================================================================================================
Shape: (6, 8)

Columns:
['S/N', 'KeyOutputProjectIndicator', 'UnitOfMeasure', 'Target', 'Actual', 'Variance', 'ReportPeriod', 'SourceDocument']

First 3 records:

,S/N,KeyOutputProjectIndicator,UnitOfMeasure,Target,Actual,Variance,ReportPeriod,SourceDocument
0,1,Environment and Waste Management,No. of Tones,59280.00,47934.5,11345.50,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
1,2,Maintenance of Township Roads,No. of Kms,113.25,46.0,67.25,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
2,3,Fire Management Services,No. of Calls,4.00,108.0,-104.00,01-Jan-2025 to 30-Jun-2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf

====================================================================================================
db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv
====================================================================================================
Shape: (55, 8)

Columns:
['ProgrammeCode', 'Programme', 'SubProgrammeCode', 'SubProgramme', 'Budget2024ZMW', 'Budget2025ZMW', 'Budget2026ZMW', 'SourceDocument']

First 3 records:

,ProgrammeCode,Programme,SubProgrammeCode,SubProgramme,Budget2024ZMW,Budget2025ZMW,Budget2026ZMW,SourceDocument
0,1,Constituency Development,779,Community Projects,34924632,43925383,48456199,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf
1,1,Constituency Development,780,Women and Youth Empowerment,11641544,12456452,13966724,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf
2,1,Constituency Development,781,CDF Administration,3063564,3278014,3675454,Chingola-Council-2026-budget-HeadMandateObjectiveSubProg.pdf

====================================================================================================
db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv
====================================================================================================
Shape: (100, 4)

Columns:
['Year', 'IncomeSource', 'ProjectedAmountZMW', 'SourceDocument']

First 3 records:

   Year       IncomeSource  ProjectedAmountZMW    SourceDocument
0  2023  Local Taxes/Rates          69655649.0  CHINGOLA-IDP.pdf
1  2024  Local Taxes/Rates          69655649.0  CHINGOLA-IDP.pdf
2  2025  Local Taxes/Rates          69655649.0  CHINGOLA-IDP.pdf

====================================================================================================
db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv
====================================================================================================
Shape: (177, 6)

Columns:
['BudgetYear', 'RevenueCategory', 'Code', 'RevenueDescription', 'ApprovedBudgetZMW', 'SourceDocument']

First 3 records:

,BudgetYear,RevenueCategory,Code,RevenueDescription,ApprovedBudgetZMW,SourceDocument
0,2024,Local taxes/rates,1,Residential,9224443.0,2024-BUDGET-CHINGOLA-MUNICIPAL-COUNCIL.pdf
1,2024,Local taxes/rates,2,Commercial,7617219.0,2024-BUDGET-CHINGOLA-MUNICIPAL-COUNCIL.pdf
2,2024,Local taxes/rates,5,Mining/Plant,65865705.0,2024-BUDGET-CHINGOLA-MUNICIPAL-COUNCIL.pdf

====================================================================================================
db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv
====================================================================================================
Shape: (14, 5)

Columns:
['BudgetStage', 'KeyActivity', 'StakeholderCategory', 'Timeline', 'SourceDocument']

First 3 records:

,BudgetStage,KeyActivity,StakeholderCategory,Timeline,SourceDocument
0,Budget preparation / formulation,LAs provide communities with SEP giving proposed dates for consultation,PAPs; OIPs; DVGs,October,citizen-engagement-strategy-.pdf
1,Budget preparation / formulation,"LAs provide WDCs with a list of proposed projects for consideration in this budget cycle, as wel...",PAPs; OIPs; DVGs,October,citizen-engagement-strategy-.pdf
2,Budget preparation / formulation,"Using the project lists provided, communities may accept or reject project proposals or make the...",PAPs; OIPs; DVGs,October,citizen-engagement-strategy-.pdf

====================================================================================================
db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv
====================================================================================================
Shape: (8, 7)

Columns:
['No', 'SubjectMatter', 'AuditFinding', 'AuditRecommendation', 'ManagementActionTaken', 'ReportPeriod', 'SourceDocument']

First 3 records:

,No,SubjectMatter,AuditFinding,AuditRecommendation,ManagementActionTaken,ReportPeriod,SourceDocument
0,1,Governance (Established Committees & Meetings),All standing committees have been established,Committees to hold meetings quartely,Atleast one meeting should be held per quarter,Jan 2025 to Jun 2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
1,2,Budget Execution,Certain budgeted programs not implemented,Management should set realistic targets,Budget review meeting held to realign the budget,Jan 2025 to Jun 2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf
2,3,Income - Own Source Revenue,Failure to collect revenue from markets (Chiwempala and Town centre markets),The routine inspection and rotation of revenue collectors should be conducted within the distric...,Management acknowleged the query and ensured that routine inspections and rotations were done on...,Jan 2025 to Jun 2025,CHINGOLA-SEMI-ANNUAL-BUDGET-PERFORMANCE-REPORT.pdf

In [ ]:
quality_reports = []

for filename, df in raw_data.items():

    for column in df.columns:

        quality_reports.append({
            "Dataset": filename,
            "Column": column,
            "DataType": str(df[column].dtype),
            "MissingValues": int(df[column].isna().sum()),
            "MissingPercent": round(
                df[column].isna().mean() * 100, 2
            ),
            "UniqueValues": int(df[column].nunique()),
            "DuplicateValues": int(
                df[column].duplicated().sum()
            )
        })

quality_df = pd.DataFrame(quality_reports)

display(quality_df)

,Dataset,Column,DataType,MissingValues,MissingPercent,UniqueValues,DuplicateValues
0,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,Section,object,0,0.0,3,14
1,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,Code,float64,0,0.0,16,1
2,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,Receipt,object,0,0.0,17,0
3,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,BudgetZMW,int64,0,0.0,11,6
4,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,ActualTo30Jun2025ZMW,int64,0,0.0,11,6
...,...,...,...,...,...,...,...
180,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,AuditFinding,object,0,0.0,8,0
181,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,AuditRecommendation,object,0,0.0,7,1
182,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,ManagementActionTaken,object,0,0.0,7,1
183,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,ReportPeriod,object,0,0.0,1,7
184,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,SourceDocument,object,0,0.0,1,7

In [ ]:
duplicate_report = []

for filename, df in raw_data.items():

    duplicate_report.append({
        "Dataset": filename,
        "Rows": len(df),
        "DuplicateRows": int(df.duplicated().sum())
    })

duplicate_df = pd.DataFrame(duplicate_report)

display(duplicate_df)

,Dataset,Rows,DuplicateRows
0,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,17,0
1,db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv,5,0
2,db-unza26-csc4792-chingola_semiannual_payments_2025.csv,8,0
3,db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv,13,0
4,db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv,5,0
5,db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv,10,0
6,db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv,15,0
7,db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv,5,0
8,db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv,139,0
9,db-unza26-csc4792-chingola_cdf_2025_applications.csv,86,0
10,db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv,5,0
11,db-unza26-csc4792-chingola_capital_output_2024.csv,10,0
12,db-unza26-csc4792-chingola_cdf_2024_applications.csv,58,0
13,db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv,16,0
14,db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv,7,0
15,db-unza26-csc4792-nchanga_cdf_2025_applications.csv,48,0
16,db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv,7,0
17,db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv,6,0
18,db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv,55,0
19,db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv,100,0
20,db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv,177,0
21,db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv,14,0
22,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,8,0

In [ ]:
cleaned_data = {}

def standardise_column_name(column):

    column = str(column).strip()

    column = re.sub(
        r"(?<!^)(?=[A-Z])",
        "_",
        column
    )

    column = column.lower()

    column = re.sub(
        r"[^a-z0-9]+",
        "_",
        column
    )

    column = column.strip("_")

    return column


for filename, df in raw_data.items():

    clean_df = df.copy()

    clean_df.columns = [
        standardise_column_name(col)
        for col in clean_df.columns
    ]

    cleaned_data[filename] = clean_df

print("Column names standardised successfully.")

Column names standardised successfully.

In [ ]:
for filename, df in cleaned_data.items():

    text_columns = df.select_dtypes(
        include=["object"]
    ).columns

    for column in text_columns:

        df[column] = (
            df[column]
            .astype("string")
            .str.strip()
        )

        # Convert empty strings to missing values
        df[column] = df[column].replace(
            {"": pd.NA, "nan": pd.NA, "None": pd.NA}
        )

print("Text cleaning completed.")

Text cleaning completed.

In [ ]:
duplicate_removal = []

for filename, df in cleaned_data.items():

    before = len(df)

    df.drop_duplicates(
        inplace=True
    )

    after = len(df)

    duplicate_removal.append({
        "Dataset": filename,
        "RowsBefore": before,
        "RowsAfter": after,
        "DuplicatesRemoved": before - after
    })

duplicate_removal_df = pd.DataFrame(
    duplicate_removal
)

display(duplicate_removal_df)

,Dataset,RowsBefore,RowsAfter,DuplicatesRemoved
0,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,17,17,0
1,db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv,5,5,0
2,db-unza26-csc4792-chingola_semiannual_payments_2025.csv,8,8,0
3,db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv,13,13,0
4,db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv,5,5,0
5,db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv,10,10,0
6,db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv,15,15,0
7,db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv,5,5,0
8,db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv,139,139,0
9,db-unza26-csc4792-chingola_cdf_2025_applications.csv,86,86,0
10,db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv,5,5,0
11,db-unza26-csc4792-chingola_capital_output_2024.csv,10,10,0
12,db-unza26-csc4792-chingola_cdf_2024_applications.csv,58,58,0
13,db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv,16,16,0
14,db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv,7,7,0
15,db-unza26-csc4792-nchanga_cdf_2025_applications.csv,48,48,0
16,db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv,7,7,0
17,db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv,6,6,0
18,db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv,55,55,0
19,db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv,100,100,0
20,db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv,177,177,0
21,db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv,14,14,0
22,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,8,8,0

In [ ]:
def convert_numeric_columns(df):

    df = df.copy()

    for column in df.columns:

        if df[column].dtype == "object":

            sample = (
                df[column]
                .dropna()
                .astype(str)
                .str.replace(",", "", regex=False)
                .str.replace("K", "", regex=False)
                .str.replace("ZMW", "", regex=False)
                .str.replace("ZMK", "", regex=False)
                .str.strip()
            )

            numeric_version = pd.to_numeric(
                sample,
                errors="coerce"
            )

            if (
                len(sample) > 0
                and numeric_version.notna().mean() >= 0.80
            ):
                df[column] = pd.to_numeric(
                    df[column]
                    .astype(str)
                    .str.replace(",", "", regex=False)
                    .str.replace("K", "", regex=False)
                    .str.replace("ZMW", "", regex=False)
                    .str.replace("ZMK", "", regex=False)
                    .str.strip(),
                    errors="coerce"
                )

    return df


for filename in cleaned_data:

    cleaned_data[filename] = convert_numeric_columns(
        cleaned_data[filename]
    )

print("Numeric conversion completed.")

Numeric conversion completed.

In [ ]:
missing_before = []

for filename, df in cleaned_data.items():

    missing_before.append({
        "Dataset": filename,
        "MissingValues": int(df.isna().sum().sum())
    })

missing_before_df = pd.DataFrame(missing_before)

display(missing_before_df)

,Dataset,MissingValues
0,db-unza26-csc4792-chingola_semiannual_revenue_2025.csv,0
1,db-unza26-csc4792-chingola_idp_selected_capital_investment_plan_2024_2033.csv,0
2,db-unza26-csc4792-chingola_semiannual_payments_2025.csv,0
3,db-unza26-csc4792-chingola_capital_projects_performance_2025_semiannual.csv,21
4,db-unza26-csc4792-chingola_citizen_engagement_strategy_objectives.csv,0
5,db-unza26-csc4792-chingola_idp_national_support_financing_2019_2023.csv,0
6,db-unza26-csc4792-chingola_debt_arrears_2025_semiannual.csv,0
7,db-unza26-csc4792-chingola_citizen_engagement_communication_plan.csv,0
8,db-unza26-csc4792-chingola_cdf_projects_2024_2026.csv,537
9,db-unza26-csc4792-chingola_cdf_2025_applications.csv,319
10,db-unza26-csc4792-chingola_idp_revenue_efficiency_2018_2022.csv,0
11,db-unza26-csc4792-chingola_capital_output_2024.csv,0
12,db-unza26-csc4792-chingola_cdf_2024_applications.csv,81
13,db-unza26-csc4792-chingola_budget_programmes_2024_2026.csv,0
14,db-unza26-csc4792-chingola_idp_strategic_outputs_2024_2033.csv,0
15,db-unza26-csc4792-nchanga_cdf_2025_applications.csv,123
16,db-unza26-csc4792-chingola_budget_economic_classification_2024_2026.csv,0
17,db-unza26-csc4792-chingola_budget_output_performance_2025_semiannual.csv,1
18,db-unza26-csc4792-chingola_budget_subprogrammes_2024_2026.csv,0
19,db-unza26-csc4792-chingola_idp_cash_flow_projections_2023_2032.csv,6
20,db-unza26-csc4792-chingola_budget_revenue_2024_2026.csv,0
21,db-unza26-csc4792-chingola_citizen_engagement_stakeholder_plan.csv,0
22,db-unza26-csc4792-chingola_internal_audit_2025_semiannual.csv,0